server:
  port: ${PORT:8080}
spring:
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:db
    driverClassName: org.h2.Driver
    username: ${DB_USER:user}
    password: ${DB_PASS:}
telegram:
  bot:
    enabled: ${TELEGRAM_BOT_ENABLED:true}
    username: ${TELEGRAM_BOT_USERNAME:username}
    token: ${TELEGRAM_BOT_TOKEN:token}
    baseUrl: ${TELEGRAM_BOT_BASE_URL:http://localhost}
result:
  send:
    schedule:
      delay: 10000
    backoff:
      period: 1000
    client:
      url: ${RESULT_HOOK_URL:https://mssg.su/h/XyKUoZB5/648645209/21081}
online:
  compile:
    client:
      url: ${COMPILE_CLIENT_URL:https://www.compilejava.net/v1/}
feign.hystrix.enabled: true
resultSend:
  ribbon:
    MaxAutoRetries: 100
    MaxAutoRetriesNextServer: 2
    retryableStatusCodes: 419
